### ISSUE TITLE
🛑 Panel Control is down

### ISSUE THREAD

**Issue by raznarlab** [Raznar-Hosting/uptime-monitor#35]
In [`a8b2fc5`](https://github.com/Raznar-Hosting/uptime-monitor/commit/a8b2fc59a04af9a3688c4efd517f159af430050d
), Panel Control (https://console-ptero.raznar.id) was **down**:
- HTTP code: 403
- Response time: 144 ms

**Comment by NotYusta** [comment]
Invalid URL
