### ISSUE TITLE
🛑 phpmyAdmin is down

### ISSUE THREAD

**Issue by raznarlab** [Raznar-Hosting/uptime-monitor#36]
In [`2453a8c`](https://github.com/Raznar-Hosting/uptime-monitor/commit/2453a8c428c72651c2defec27cb2c9d31a9bd944
), phpmyAdmin (https://phpmyadmin.raznar.id) was **down**:
- HTTP code: 403
- Response time: 80 ms

**Comment by NotYusta** [comment]
Invalid URL
