### ISSUE TITLE
🛑 Panel Control is down

### ISSUE THREAD

**Issue by raznarlab** [Raznar-Hosting/uptime-monitor#41]
In [`5f8fda3`](https://github.com/Raznar-Hosting/uptime-monitor/commit/5f8fda334b183bf88330f93eb2c2694e1c5d5bbe
), Panel Control (https://console-ptero.raznar.id) was **down**:
- HTTP code: 403
- Response time: 136 ms

**Comment by NotYusta** [comment]
Invalid URL
